# Generated by Django 4.2.23 on 2025-06-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_hash',
            field=models.CharField(default=12321, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
